require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.completion"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autoformat"
require "user.autopairs"
require "user.comments"
require "user.gitsigns"
require "user.nvim-tree"
require 'nvim-tree'.setup {} -- https://github.com/nvim-tree/nvim-tree.lua/issues/767
require "user.bufferline"
